//hashing.js

// Hashing is a technique used to map data to a fixed-size array, known as a hash table, in order to efficiently store and retrieve data. It is commonly used in data structures and algorithms to speed up operations such as searching, insertion, and deletion.

// Hashing works by applying a hash function to the input data, which generates a unique hash code or hash value. This hash code is used as an index to store the data in the hash table. When retrieving the data, the hash function is applied again to generate the hash code, which is used to look up the data in the hash table.

// Hashing has several advantages, including:
// - Fast access to data: Hashing allows for constant-time access to data, making it efficient for storing and retrieving data.
// - Efficient searching: Hashing can be used to quickly search for data in a large dataset by mapping the data to a fixed-size array.
// - Collision resolution: Hashing provides techniques to handle collisions, where multiple data elements map to the same index in the hash table.

// There are different types of hash functions and collision resolution techniques that can be used in hashing. Some common hash functions include:
// - Division method: The hash code is generated by taking the remainder of the division of the input data by the size of the hash table.
// - Multiplication method: The hash code is generated by multiplying the input data by a constant factor and taking the fractional part of the result.
// - Folding method: The input data is divided into equal-sized parts, which are then added together to generate the hash code.

// Collision resolution techniques are used to handle cases where multiple data elements map to the same index in the hash table. Some common collision resolution techniques include:
// - Chaining: In chaining, each index in the hash table stores a linked list of data elements that map to the same index.
// - Open addressing: In open addressing, when a collision occurs, the algorithm searches for an empty slot in the hash table to store the data element.

//Example of hashing using the division method and chaining collision resolution technique:

class HashTable {
    constructor(size) {
        this.size = size;
        this.table = new Array(size).fill(null).map(() => []);
    }

    hash(key) {
        return key % this.size;
    }

    insert(key, value) {
        const index = this.hash(key);
        this.table[index].push({ key, value });
    }

    search(key) {
        const index = this.hash(key);
        for (const item of this.table[index]) {
            if (item.key === key) {
                return item.value;
            }
        }
        return null;
    }

    delete(key) {
        const index = this.hash(key);
        this.table[index] = this.table[index].filter(item => item.key !== key);
    }
}

// Example usage:
const hashTable = new HashTable(10);
hashTable.insert(5, 'apple');
hashTable.insert(15, 'banana');
hashTable.insert(25, 'cherry');

console.log(hashTable.search(5)); // Output: 'apple'
hashTable.delete(5);
console.log(hashTable.search(5)); // Output: null

// In this example, we create a HashTable class that uses the division method for hashing and the chaining collision resolution technique. We insert key-value pairs into the hash table, search for a key, and delete a key from the hash table. The hash function generates the hash code by taking the remainder of the division of the key by the size of the hash table. The chaining technique is used to handle collisions by storing data elements that map to the same index in a linked list.

//space complexity: O(n) where n is the number of elements in the hash table.
//time complexity: O(1) for insertion, deletion, and search operations in the best case, O(n) in the worst case.

//Example of hashing using the multiplication method and open addressing collision resolution technique:

class HashTable {
    constructor(size) {
        this.size = size;
        this.table = new Array(size).fill(null);
    }

    hash(key) {
        const A = (Math.sqrt(5) - 1) / 2;
        return Math.floor(this.size * ((key * A) % 1));
    }

    insert(key, value) {
        let index = this.hash(key);
        while (this.table[index] !== null) {
            index = (index + 1) % this.size;
        }
        this.table[index] = { key, value };
    }

    search(key) {
        let index = this.hash(key);
        while (this.table[index] !== null) {
            if (this.table[index].key === key) {
                return this.table[index].value;
            }
            index = (index + 1) % this.size;
        }
        return null;
    }

    delete(key) {
        let index = this.hash(key);
        while (this.table[index] !== null) {
            if (this.table[index].key === key) {
                this.table[index] = null;
                return;
            }
            index = (index + 1) % this.size;
        }
    }
}

// Example usage:
const hashTables = new HashTable(10);
hashTables.insert(5, 'apple');
hashTables.insert(15, 'banana');
hashTables.insert(25, 'cherry');

console.log(hashTables.search(5)); // Output: 'apple'
hashTables.delete(5);
console.log(hashTables.search(5)); // Output: null

// In this example, we create a HashTable class that uses the multiplication method for hashing and the open addressing collision resolution technique. We insert key-value pairs into the hash table, search for a key, and delete a key from the hash table. The hash function generates the hash code by multiplying the key by a constant factor and taking the fractional part of the result. The open addressing technique is used to handle collisions by searching for an empty slot in the hash table to store the data element.

//space complexity: O(n) where n is the number of elements in the hash table.
//time complexity: O(1) for insertion, deletion, and search operations in the best case, O(n) in the worst case.

//Example of hashing using the folding method and chaining collision resolution technique:

class HashTable {
    constructor(size) {
        this.size = size;
        this.table = new Array(size).fill(null).map(() => []);
    }

    hash(key) {
        const str = key.toString();
        let hash = 0;
        for (let i = 0; i < str.length; i += 2) {
            hash += parseInt(str.slice(i, i + 2), 10);
        }
        return hash % this.size;
    }

    insert(key, value) {
        const index = this.hash(key);
        this.table[index].push({ key, value });
    }

    search(key) {
        const index = this.hash(key);
        for (const item of this.table[index]) {
            if (item.key === key) {
                return item.value;
            }
        }
        return null;
    }

    delete(key) {
        const index = this.hash(key);
        this.table[index] = this.table[index].filter(item => item.key !== key);
    }
}

// Example usage:
const hashTabless = new HashTable(10);
hashTabless.insert(5, 'apple');
hashTabless.insert(15, 'banana');
hashTabless.insert(25, 'cherry');

console.log(hashTabless.search(5)); // Output: 'apple'
hashTabless.delete(5);
console.log(hashTabless.search(5)); // Output: null

// In this example, we create a HashTable class that uses the folding method for hashing and the chaining collision resolution technique. We insert key-value pairs into the hash table, search for a key, and delete a key from the hash table. The hash function generates the hash code by dividing the input data into equal-sized parts and adding them together. The chaining technique is used to handle collisions by storing data elements that map to the same index in a linked list.

//time complexity: O(1) for insertion, deletion, and search operations in the best case, O(n) in the worst case.

//space complexity: O(n) where n is the number of elements in the hash table.

